[phases.setup]
nixPkgs = ["python3", "nodejs", "npm"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd frontend && npm install --production && npm run build && rm -rf node_modules && cd .."
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python app.py"